import pathlib

# Constantes ENV string
MATCH = 'MATCH'
MISMATCH = 'MISMATCH'
GAP_PENALTY = 'GAP_PENALTY'
FILE_FORMAT  = 'FILE_FORMAT'
MIN_SEQUENCES = 'MIN_SEQUENCES'
QUERY_SEQUENCE = 'QUERY_SEQUENCE'
DB_HOMOLOGOUS_SEQUENCES = 'DB_HOMOLOGOUS_SEQUENCES'
DB_BLAST = 'DB_BLAST'
ALL_ENV_VARIABLES = [MATCH, MISMATCH , GAP_PENALTY , FILE_FORMAT  , MIN_SEQUENCES , QUERY_SEQUENCE , DB_HOMOLOGOUS_SEQUENCES , DB_BLAST]

# Constants PATH Clustal
CLUSTALW_PATH = str(pathlib.Path(__file__).parent.parent.parent.parent.resolve()) + "/clustalw2"

